server:
  port: ${SERVER_PORT:8080}

  app:
    //127.0.0.1
  backEndUrl: ${http://192.168.100.232:8080}

minio:
  endpoint: ${MINIO_ENDPOINT:http://192.168.100.171:9000}
  accesskey: ${MINIO_ASSESSKEY:SA8M7D37BJHLEY68TOOU}
  secretkey: ${MINIO_SECRETKEY:MSJ1ng150g1oH+1QBZ2yBzwuxbNCWoqOt3Sp42Lt}
  bucket: ${MINIO_BUCKET:n1krmxsvs6}